theme = "solarized-dark" 
icons = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MiB/{MTg} GiB"

[[block]]
block = "custom"

on_click = "scrot -e 'mv $f ~/Pictures'"
command = "echo " 

[[block]]
block  = "battery"

[[block]]
block = "sound"

[[block]]
block = "pacman"

[[block]]
block = "music"
player = "pragha"
buttons = ["prev", "play", "next"]

[[block]]
block = "time"
interval = 1
format = "%a %m/%d %R"

[[block]]
block = "custom"
command = "echo   $(light)"
on_click = "sh /bl.sh"
interval = 5

[[block]]
block = "custom"
command = "echo   Tools"
on_click = "revenge-tools"
